distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.13-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
android.useAndroidX=true
android.enableJetifier=true
# Increase Gradle memory limits
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Use the Gradle daemon to speed up builds
org.gradle.daemon=true

# Enable parallel execution for faster builds
org.gradle.parallel=true
kotlin.code.style=official